mozilla-l10n/langchecker

views/listsitesforlocale.inc.php
The only time I merge directly I manage to mess up (copying code from different branches with different class names :-\)
=> Fix class name (Bugzilla -> _Bugzilla)

config/locales.inc.php, config/sources.inc.php, media/css/langchecker.css, views/listsitesforlocale.inc.php
* Remove $mozilla_europe array (unused).
* Use $mozilla as list of all locales somehow supported by langchecker (but not necessarily by mozilla.org). Remove from this array all dropped locales.
* Add a list of locales supported on Firefox Desktop (e.g. tiles, FHR).
* Use $mozillaorg as list of locales supported by mozilla.org. Use it for mozilla.org pages instead of $mozilla
* Move other arrays of locales in sources, use the same style and order them alphabetically (no changes to locales for this part)
Also don't display empty website in listsitesforlocale, stopping at the beginning if they're not supported.
=> Reorganize sources and list of locales

views/errors.inc.php
Warning happens if the locale has tags, but reference doesn’t (in my case it was a misspelled ```## active ##``` tag).
=> Fix warning on errors view

scripts/import_transvision_id, scripts/import_transvision_string
Starting from v3.6 mozilla.org results are as other repositories: if translation is missing the string is empty, not identical to English anymore.
Also improved import from id to avoid warnings (we filter out empty strings, but still try to check these locales).
=> Improve scripts to import translations from Transvision

scripts/lang_update
As explained on php.net for [array_merge](http://php.net/manual/en/function.array-merge.php).
> If the input arrays have the same string keys,
> then the later value for that key will overwrite
> the previous one.
The current strings should always be the last element of array_merge.
=> lang_update: don't overwrite existing string when importing from other files

views/errors.inc.php
Report if the string ID is different from the string value.
Already fixed a few errors reported
http://viewvc.svn.mozilla.org/vc?revision=138173&view=revision
=> Error view: Add check for 'translated' strings in reference files

config/sources.inc.php, media/css/langchecker.css, views/countstrings.inc.php, views/export.inc.php, views/listpages.inc.php, views/listsitesforlocale.inc.php
Hide them from JSON (for the webdashboard) and from the main view used by localizers.
Don't use them for counting strings.
Display them differently in listpages.
=> Support concept of 'obsolete' lang files

classes/Langchecker/DotLangParser.php, classes/Langchecker/Utils.php, config/settings.inc.php.ini, templates/template.inc.php, tests/units/Langchecker/DotLangParser.php
- faster Utils::isUTF8() by giving the path of the Magic mime file on the server
- store parsed English reference files in a static property instead of reparsing them every time
- in DotLangParser::ParseFile() avoid reparsing the whole file in the main loop for file metadata once we are already parsing strings
- Utils::starstWith() && Utils::leftStrip() have specific cases for searching ; and # with less calculation (on the error page we call these functions up to 2 million times)
- new DotLangParser::getMetaTags() utility function to return the list of tags we use in lang files
- moved parsing of reference metadata to a private DotLangParser::extractReferenceMetaData() property to make parseFile() more readable
Locally, the new version is 4 times faster for me, since this page is heavy …
=> Issue #312: improve performance of error page

classes/Langchecker/DotLangParser.php, classes/Langchecker/LangManager.php, tests/units/Langchecker/DotLangParser.php, views/countstrings.inc.php
- DotLangParser::extract_metadata static boolean property, allows a view to not extract any metadata when parsing lang files
- LangManager::error_checking static boolean property, allows a view to not look for errors in strings when parsing lang files
- Update main loop in DotLangParser::ParseFile() to test most common case first (translation exists)
- many small nitpicks and cleanups
Performance gains are mostly on the 'count' view (40% for me) but other views also benefit from a small speedup because of the code reorganization (~10%).
=> More performance improvement, mostly on the action=count view:

.travis.yml
- use sudo:false to force the use of Docker based Travis which is faster and can cache dependencies
- use prefer-source for composer because Travis is always hitting the github API limit and will fallback to that anyway
- use fast-finish:true in matrix section, allows to get informed that the build failed faster, if PHP 5.5 build failed and 5.6 build is not started, Travis will not wait for 5.5 to complete to send the failure notificatione
=> Faster Travis config

config/sources.inc.php
Received a request to remove some pages from 'et' and don't want to lose existing translations.
Will probably need to add 'uk' to the consumer page too.
=> Use a distinct set of locales for some FxOS pages

classes/Langchecker/LangManager.php, classes/Langchecker/Utils.php, tests/units/Langchecker/Utils.php, views/listsitesforlocale.inc.php
Would this work? Still have to actually write the tip itself in listsitesforlocale.inc.php instead of the current placeholder.
Displaying the tip if:
- We caught a Python var error in the file (since we currently don't display any advice about what's wrong)
- There are Python variables in untranslated strings
Not displaying it if there is no variables in the file, or if the variables are all in translated strings without error.
=> Add a tip about variable formats - fixes #311

classes/Langchecker/DotLangParser.php, tests/testfiles/dotlang/test_comments.lang, tests/units/Langchecker/DotLangParser.php
We currently lose the first comment if the file starts with the comment and not with ´## NOTE:
=> Read comment even if it's the first line of the file

classes/Langchecker/LangManager.php, views/errors.inc.php, views/globalstatus.inc.php
In the Errors view we’re parsing each localized file twice just to get tags.
This cuts the time needed to display this page in half.
=> Add Tags to analyzeLangFiles return value

classes/Langchecker/DotLangParser.php, classes/Langchecker/LangManager.php, media/css/langchecker.css, tests/testfiles/dotlang/it/page.lang, tests/testfiles/dotlang/toto.lang, tests/units/Langchecker/DotLangParser.php, tests/units/Langchecker/LangManager.php, views/errors.inc.php, views/listsitesforlocale.inc.php
Pootle and Pontoon sometimes try to store multiline strings in .lang files (localizers create new lines in the editor). Sometimes localizers forget to remove the English “translation” too.
While lang_update already removes them, it’s useful to have a check in the errors page.
=> Report extra strings in lang files as errors

classes/Langchecker/DotLangParser.php, tests/units/Langchecker/DotLangParser.php
We don’t need these tags for localized files. It also simplifies the main parser method code.
=> Move parsing of ##NOTE and ##URL  to extractReferenceMetaData method

app/classes/Langchecker/RawManager.php, app/classes/Langchecker/Utils.php, tests/testfiles/misc/git_log.txt, tests/units/Langchecker/RawManager.php
Again, based on #401 so will need rebase after that's reviewed and fixed.
Fixes #406: the current implementation takes about 200ms for each file. That's 10.8s on a page like Italian (27 files x 2), even caching en-US results is not enough.
The idea is to get timestamps for all files calling `git log` only once, and cache the result. Even without cache (first load), the Italian page loads in less than 3 seconds. Second load goes back to 0.2s
=> Provide a faster way to get last update timestamp from Git log

app/classes/Langchecker/Bugzilla.php, app/controllers/optin.php, app/templates/optin.twig, tests/units/Langchecker/Bugzilla.php, web/assets/css/langchecker.css, web/assets/js/base.js, web/assets/js/optin.js
Use checkboxes to select pages, use a button to open the URL
Reason for the redesign: nobody uses the link at the bottom of the page, I keep receiving multiple bugs filed at the same time from the same localizer.
I asked them and the link at the bottom is either unclear or not visible.
This is based on #401, so it will need to be rebased or fixed after that. Filing a PR to avoid forgetting about it.
=> Optin redesign

app/scripts/untracked_files
Just noticed that firefox/independent.lang was removed from locales but not reference, which means it’s still exposed on Transvision and Pootle.
It’s better having the reference locale always included.
=> untracked_files script: include reference, display relative path by default

app/config/settings.inc.php.ini, app/config/sources.inc.php, app/scripts/update_sources
One last update: make the repos storage structure a bit less cryptic, create a script that can be used to update all repos from a single cronjob.
I'm tempted to take it one step further, and store in settings.php only one or two paths (like GIT_PATH and SVN_PATH) like we do in Transvision, and eventually add a ´local_folder´ to the array to specify a different checkout folder.
Thoughts?
Based on #401.
=> Reorganize sources, add script to update repos

app/config/locales.inc.php, app/config/sources.inc.php
While I absolutely understand the need to have arrays easy to map to shipping versions, the lhe last updates left quite some issues. This is the list of file untracked only currently in mozilla.org
```
af/firefox/android/index.lang
bn-BD/firefox/android/index.lang
cak/firefox/android/index.lang
fa/firefox/android/index.lang
sat/firefox/android/index.lang
tsz/firefox/android/index.lang
ach/firefox/ios.lang
af/firefox/ios.lang
an/firefox/ios.lang
as/firefox/ios.lang
ast/firefox/ios.lang
be/firefox/ios.lang
bn-BD/firefox/ios.lang
brx/firefox/ios.lang
bs/firefox/ios.lang
ca/firefox/ios.lang
en-GB/firefox/ios.lang
es-AR/firefox/ios.lang
et/firefox/ios.lang
eu/firefox/ios.lang
ff/firefox/ios.lang
fi/firefox/ios.lang
gn/firefox/ios.lang
gu-IN/firefox/ios.lang
he/firefox/ios.lang …
```
=> Fix supported locales for landing pages (Android, iOS)

app/config/sources.inc.php
I noticed some files like screenshots_2_0.lang were still displayed on locale dashboards (for Arabic, for instance). This will help localizers set priorities and prevent them from translating stuff that won’t be used.
@flodolo does that look good to you?
I imagine we’ll remove the files at some point, but this is a first step
=> Remove Firefox OS marketing files from locale dashboards

app/config/locales.inc.php
This caused https://github.com/mozilla-l10n/www.mozilla.org/commit/d7252554f194b68685ed82801a597181c4d2b933#diff-3057f915bb835cd221b0b1235ec14057
en-US shouldn't be in the list of locales supported for a page.
CC @TheoChevalier 
Not sure if you want to update the list also at https://github.com/mozilla-l10n/stores_l10n/blob/15633f598a78357575630fdc235f9cbccc4c6ed3/app/classes/Stores/Project.php#L43
I might fix WebStatus' API to not expose en-US for iOS at all.
=> Remove en-US from $ios_locales

app/classes/Langchecker/Utils.php, app/config/settings.inc.php.ini, app/controllers/errors.php, app/controllers/export.php, app/controllers/listsitesforlocale.php, app/inc/init.php, tests/units/Langchecker/Utils.php
Undo the last patch and catch exception on finfo(), store information about lib magic in a private static variable.
=> Remove $disable_magic setting, properly catch exception in finfo()

app/config/locales.inc.php, app/config/sources.inc.php
Add new locales to mozilla.org pages:
- bug 1343325 (ncj)
- bug 1342627 (zam)
Add sv-SE to an opt-in page: bug 1342816
=> bootstrap locales ncj, zam; add sv-SE to thunderbird/channel.lang

app/config/sources.inc.php
Not sure why the deadline for What's New skips from Firefox 51 to 52 in this file... doesn't make much sense to me. Updated with latest version and dates nevertheless.
=> Track Appstores files for 52 and 53 beta 

app/config/sources.inc.php
Not removing it for the other completed locales, because there are strings we can import in next surveys
=> Remove Maker Party survey for Polish

app/config/sources.inc.php, app/config/store_locales.inc.php
=> Store locales: make sure they're supported on mozilla

app/config/sources.inc.php
It’s not as bad as it looks, we can talk about it later today, but I want to expose it before teams work on their missing strings (for French and Spanish)
=> Copyright content, March

app/config/sources.inc.php
Per bug 1364268.
NOTE: 
- I listed es-ES as the locale, since the file lives in the corresponding repo. The file is technically in "es".
=> add file mozorg/about/governance/policies/participation.lang

app/config/sources.inc.php, app/scripts/activate_firefox_shared
- add onboarding.lang
- add firefox/products/developer.lang
- update deadline to onboarding, developer and sync files to 8/20
- change file order under firefox/products/...
NOTE:
- to be obsolete developer.lang supports firefox locales, not mozillaorg.
- new firefox/products/developer.lang is set to be supported by mozillaorg locales. should we change?
- did not change priority for sync or new developer file.  should we? Sync 1 and dev lower?
=> Update file per mozilla.org PR #172

app/config/sources.inc.php
Pocket email is for Polish only.
=> add Pocket email per bug 1384394

app/classes/Langchecker/Utils.php, tests/units/Langchecker/Utils.php
Similar issue to bug 1461199, causing false positive on https://l10n.mozilla-community.org/langchecker/?locale=fr#snippets/2018/may2018.lang
=> Decode HTML entities when counting characters

app/config/sources.inc.php
- German only per email team
- Other locales (pt-br, ru, id, pl, de, es, fr) could be supported at a much later time. 
- This file is different from the other newsletter file which has a different set of locales.
=> Newsletter per bug 1467252

app/config/sources.inc.php
@flodolo Legal gave an ok to open up side panel to all locales. However, the Mozilla PN (main page) will be limited to the currently supported languages. I left the deadline the same as FAQ page.
=> change privacy index page locale list

app/config/sources.inc.php
Add new file firefox/accounts-2018.lang and deadline.
This page will go live on Nov 27. However, the localized page will go live as soon as it is activated.
=> add a new file and deadline per PR256

app/config/locales.inc.php
I saw these two are still in the mozilla.org locale list and thought they should be removed. 
Also, I have not been able to see mozilla.org/bn go live.
=> remove locales bn-BD, bn-IN

app/config/sources.inc.php
Only for en-GB, en-CA, de, and fr. We'll expand to more locales later.
=> Add firefox/accounts-2019.lang

app/config/sources.inc.php
Lang file added in https://github.com/mozilla-l10n/www.mozilla.org/pull/326
Targeting "Tier One" locales (English, French, German) for Fx69 but we'll soon have a new evergreen default whatsnew page for all locales.
=> Add whatsnew_69

app/config/sources.inc.php
I was mistaken previously; this should be exposed to all locales.
=> Expand whatsnew_69 to all locales

app/config/sources.inc.php
Initially limited to English, French, and German at launch, might expand to more later if it performs well.
See https://github.com/mozilla-l10n/www.mozilla.org/pull/330
=> Add lifecycle page 1

app/config/sources.inc.php
Strings added in https://github.com/mozilla-l10n/www.mozilla.org/pull/334
The new nav strings appear in a separate Firefox navbar that will be English-only until translation is complete.
The footer strings are all new and will be English-only until translation is complete.
=> Update navigation.lang, add footer.lang

app/config/sources.inc.php
Initially just for French and German for in-house translation. We expect there may be changes to this page in the near future and we can expand to more locales once things settle down.
=> Add firefox/home-master.lang

app/config/sources.inc.php
Five new pages comparing Firefox to other major browsers, as well as a shared lang file.
We'll be handling French and German in-house. This is a LOT of text so all other locales are lowest priority, no deadline, and purely opt-in so localizers should only work on these pages if they want to.
Lang files added in https://github.com/mozilla-l10n/www.mozilla.org/pull/371
=> Add browser comparison pages

app/config/sources.inc.php
- `download_button.lang` removed in https://github.com/mozilla/bedrock/pull/8699
- `firefox/new/reggiewatts.lang` removed in https://github.com/mozilla/bedrock/pull/6576
- `firefox/new/wait-face.lang` removed in https://github.com/mozilla/bedrock/pull/6576
- `firefox/profile-per-install.lang` removed in https://github.com/mozilla/bedrock/pull/6700
- `firefox/sendto.lang` removed in https://github.com/mozilla/bedrock/pull/8783
- `firefox/switch.lang` removed in https://github.com/mozilla/bedrock/pull/8599
- `footer.lang` removed in https://github.com/mozilla/bedrock/pull/8689
- `mozorg/internet-health/*.lang` removed in https://github.com/mozilla/bedrock/pull/8907
- `mozorg/mission.lang` removed in https://github.com/mozilla/bedrock/pull/7679
- `mozorg/plugincheck-update.lang` removed in …
=> Remove unused .lang files
