mozilla-l10n/langchecker

- classes/Webdashboard/Bugzilla.php
- config/locales.inc.php
- config/sources.inc.php
Also ignore errors in Bugzilla by default for now, since we're missing all locale components
> Bug 1117893 - Add new African locales

- config/sources.inc.php
Added locales: cs, de, el, es, pl, pt-BR.
> Bug 1120574 - Enable more locales for screenshots 2.0

- views/countstrings.inc.php
Realized the other day with en-GB that I don’t know where to look for the amount of strings translated by a single locale.
Renamed old variable `$todo` for clarity, made table sortable.
> Display translated+total strings and files in action=count

- classes/Langchecker/Project.php
- config/sources.inc.php
- media/css/langchecker.css
- templates/template.inc.php
- tests/units/Langchecker/Project.php
- views/listsitesforlocale.inc.php
- views/optin.inc.php
Opt-in status is determined by a `opt-in` flag associated with the file.
> Create a view to display opt-in pages for a locale

- .gitignore
- classes/Langchecker/DotLangParser.php
- classes/Langchecker/Project.php
- media/css/langchecker.css
- tests/testfiles/dotlang/toto.lang
- tests/units/Langchecker/DotLangParser.php
- tests/units/Langchecker/Project.php
- views/export.inc.php
- views/globalstatus.inc.php
- views/listpages.inc.php
- views/optin.inc.php
Used to associate a demo URL to a .lang file.
Update JSON export and some views (opt-in, global status, list pages) to display links to the page.
> Add support for ## URL: tag

- classes/Langchecker/Utils.php
- config/sources.inc.php
- views/countstrings.inc.php
- views/globalstatus.inc.php
- views/listpages.inc.php
- views/optin.inc.php
Space between function/foreach and () per
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-codi
ng-style-guide.md#55-foreach
> Add 3 pages to pt-BR, fix coding style nits

- .travis.yml
Also testing if GitHub sends a notice for the new PR
> Add IRC notifications from Travis

- scripts/import_transvision_id
- scripts/import_transvision_string
- scripts/lang_update
- scripts/mark_active
Also clean up syntax with php-cs
Currently import from external files is broken.
> lang_update: fix import from other files

- config/sources.inc.php
They’re already completely localized on Pootle
> Add opt-in pages to 'sat'

- config/sources.inc.php
> Add opt-in pages to 'uk'

- views/globalstatus.inc.php
No point in showing the number and determine coverage.
> Global status: change footer for files that can't be activated

- .gitignore
- .travis.yml
- Make travis test PHP 5.5 and 5.6 instead of 5.4 and 5.5
- Add .phpintel to list of ignored folders (Sublime Text Codeintel data)
> Update config files:

- classes/Langchecker/LangManager.php
(Started playing with blackfire.io)
Reduce number of checks for Python errors (check only if the string contains '%'), removes about 1s on my VM.
> Improve performances in Errors view (Python Checks)

- classes/Langchecker/Project.php
- media/css/langchecker.css
- scripts/mark_active
- tests/testfiles/config/sources.php
- tests/units/Langchecker/Project.php
- views/activation.inc.php
- views/countstrings.inc.php
- views/export.inc.php
- views/globalstatus.inc.php
- views/listpages.inc.php
- views/listsitesforlocale.inc.php
* Add Project::isObsoleteFile method + tests
* Don’t display them in the activation view
* Display a warning in global status header when a file is obsolete
* Ignore obsolete files in mark_active
> Improve management of obsolete files

- config/locales.inc.php
- config/sources.inc.php
* Create array for fxos and Fennec locales
* Add firefox/new to Fennec locales
> Add 'cak', 'tsz', reorganize locales

- config/sources.inc.php
Files were pushed by kohei on /trunk
> Track thunderbird/index.lang in langchecker

- composer.json
- config/locales.inc.php
- config/sources.inc.php
- scripts/export_surveys
Also add survey for Hello and Firefox 42 Beta+Release
> Create script to export surveys in Excel format for SurveyGizmo

- scripts/mark_not_active
I've been using it for a while, no point in leaving it out of the main repo.
> Add script to remove active tag

- views/export.inc.php
Fix issue #379.
Cost in terms of time is lower than expected (~20ms on my VM).
> Expose UTF-8 errors in JSON

- app/config/locales.inc.php
- app/config/sources.inc.php
Also move Locamotion locales to locales.inc.php
> Bug 1226674 - [gn] bootstrap Guarani on GitHub and the web dashboard

- app/scripts/untracked_files
Pages are destined for removal, since Persona is going to disappear in
10 months.
> Temporarily exclude persona/ from untracked files

- app/config/sources.inc.php
- app/scripts/untracked_files
Waiting for a couple of pull requests to be merged, leaving PR around in the meantime.
> Clean up obsolete files

- app/config/sources.inc.php
* Drop marketing, firefox-updater
* Move add-ons to GitHub
* Reorganize FxOS Marketing and drop slogans as a separate repository
> Bug 1245411 - Update tracked repository

- app/classes/Langchecker/GetTextManager.php
- app/scripts/add_tags
- app/scripts/export_surveys
- app/scripts/import_locamotion
- app/scripts/import_po
- app/scripts/lang_update
- app/scripts/mark_active
- app/scripts/untracked_files
Also update commenting style in some other scripts
> Reduce console output of lang_update and import_locamotion

- app/config/sources.inc.php
- app/scripts/export_surveys
Move only Hello survey to the engagement-l10n repository
> Drop surveys as a standalone repository

- app/config/locales.inc.php
- app/config/sources.inc.php
@flodolo , if you want to give it a look when you have time (I shouldn't have messed anything, but just to be sure)
> Add Thunderbird channel page

- app/classes/Langchecker/Project.php
- app/scripts/untracked_files
- tests/units/Langchecker/Project.php
List also folders for locales completely unknown.
> Update untracked script

- app/config/locales.inc.php
- app/config/sources.inc.php
Bug 1259200 and bug 1255850
Waiting for Appstores update before merging
> Update iOS shipping locales, add Arabic experiment to app stores

- app/config/sources.inc.php
refer to bug 1311152 for languages and deadline.
> add info on snippets nov2016 

- app/config/locales.inc.php
- app/config/sources.inc.php
- add nv to locale page
- add nv to mozilla.org related pages.
> Add Navajo (nv) locale

- app/config/sources.inc.php
* mozorg/about/history-details.lang
* mozorg/contribute/index.lang
> add two files to af: bug 1315537

- app/config/sources.inc.php
- add snippets dec2016; 
- remove firefox/win10-welcome
> Snippets (bug 1318151); bedrock/pull/4463

- app/config/sources.inc.php
> add mozorg/internet-health.lang info

- app/config/sources.inc.php
As per Inma’s request, moving to es
> Move Spanish eoy emails

- app/config/locales.inc.php
- app/config/sources.inc.php
- Add new locale "am" to mozilla.org key pages
- Add new snippets Jan2017 and de
> add new locale am, add snippets in de

- app/config/sources.inc.php
Flod, may I use your eyes when you have a moment? Should be pretty straightforward, but y’know…
> Fundraising email #3, Thank you snippet

- app/config/sources.inc.php
> add pt-BR to two files per bug 1326188

- app/config/locales.inc.php
- app/config/sources.inc.php
> add kab to Thunderbird files

- app/config/sources.inc.php
> add ko to internet-health file

- app/config/sources.inc.php
(Sorry for the noise in the diff, you’re looking at emails/2017/fundraising_thank_you.lang )
> Fundraising Thank You email

- app/config/sources.inc.php
ko: bug 1334117
pt-BR: bug 1333379
> add ko, pt-BR to mozorg/internet-health/privacy-security.lang

- app/config/sources.inc.php
Stealing this one to enable it before the weekend
> Bug 1336092 - Add foundation/index.lang to pt-BR

- app/config/sources.inc.php
bug 1336204: March snippets
bug 1337362: add kab to two files
> Bugs 1336204 and 1337362

- app/config/sources.inc.php
> add uk to internet-health.lang

- app/config/sources.inc.php
* foundation/index.lang
* mozorg/internet-health/privacy-security.lang
> add zh-TW to four files per bug 1341157

- app/config/sources.inc.php
Also stop using the hack for Arabic, they’re moving to beta next cycle
> Remove old whatsnew pages for Android and iOS

- app/config/sources.inc.php
> add apr2017.lang in snippets

- app/config/sources.inc.php
per PR https://github.com/mozilla-l10n/www.mozilla.org/pull/145#pullrequest
> add new digital-inclusion.lang, change deadlines

- app/config/locales.inc.php
- app/config/sources.inc.php
> add snippet file apr2017_b.lang

- app/config/sources.inc.php
bug 1348046 - kab
bug 1348065 - cy
bug 1344270 - new file: Open Innovation
> IH subpages: add new file; add locales to existing subpages; reorder files

- app/config/sources.inc.php
Bug 1349127 - add af
Bug 1348780 - add pt-BR
Bug 1281144 - firefox/all.html
> add firefox/all.lang; add new locales to IH subpages

- app/config/sources.inc.php
add locale af to open-innovation.lang
> add locale af to file per bug 1350860

- app/config/sources.inc.php
> Add es-MX to 4 internet health pages

- app/config/sources.inc.php
> Welcome message for es, pl

- app/config/sources.inc.php
en-GB:
* foundation/advocacy.lang
* foundation/index.lang
* foundation/issues.lang
* foundation/leadership-network.lang
* mozorg/internet-health/privacy-security.lang
uk: 
* mozorg/internet-health/privacy-security.lang
> add locales en-GB and uk to files per bugs 1356910 & 1356876 

- app/config/sources.inc.php
* mozorg/internet-health/privacy-security.lang
> add locale es-CL to files per bug 1357115

- app/classes/Langchecker/LangManager.php
- tests/units/Langchecker/LangManager.php
> Ignore ٪ symbols when reporting error for percentage

- app/config/sources.inc.php
Bug 1358841
Bug 1359484
PR 4774
> add whatsnew_50, update deadlines, add pt-BR to file

- app/config/sources.inc.php
> Paperstorm comms

- app/config/sources.inc.php
- Two new IH subpages
- Update three existing IH subpages
- Update three Firefox subpages.
> For PRs 4787, 4783, 4820 and 4798

- app/classes/Langchecker/DotLangParser.php
- tests/testfiles/dotlang/toto.lang
- tests/units/Langchecker/DotLangParser.php
> Allow use of trailing space for translations starting with #

- app/config/sources.inc.php
> Paperstorm email

- app/config/sources.inc.php
> Paperstorm email Italian

- app/config/sources.inc.php
A bit overkill, but we might add more locales, so this will be handy (Also Piotr asked for it)
> Updated footer for Polish

- app/config/sources.inc.php
Add locale fa to 
- internet-health, 
-  internet-health/privacy-security
> bug 1365221

- app/config/locales.inc.php
- app/config/sources.inc.php
Also set cak as desktop locale
CC @peiying2
> Add opt-in pages to Pontoon locales

- app/config/sources.inc.php
- app/config/store_locales.inc.php
Also clean up obsolete deadlines
> Bug 1363041 - Add support for Fennec nightly

- app/config/locales.inc.php
- app/config/sources.inc.php
Bugs 1367180, 1367179, and 1367162
> add locales dsb, hsb, sw to files

- app/config/locales.inc.php
- tests/integrity/source_integrity.php
Removed: bm, ee, ha, ig, ln, mg, tn, yo
> Add tests for Locamotion locales, remove obsolete ones

- app/config/sources.inc.php
Remove opt-in tag from manifesto, lower priority
> Bug 1368403 - Add opt-in pages to kk

- app/config/sources.inc.php
Also included the IH shared file.
> add locale sl to 9 files per bug 1371791

- app/config/sources.inc.php
Let’s chat about this in the PM meeting
> Focus Android pl

- app/classes/Langchecker/Project.php
- tests/functional/api.php
- tests/units/Langchecker/Project.php
Also includes en-GB in Englishes.
Fixes #667
> Include 'es' in coverage stats

- app/config/sources.inc.php
Want to get this out, independent from the mozilla.org stuff. This is more straight forward.
> add snippets aug2017 per bug 1381592

- app/config/sources.inc.php
reference bugs 
- 1385406 - sk
- 1385692 - no-NO
> add locales sk and no-NO to files

- app/config/sources.inc.php
- app/scripts/activate_firefox_shared
add two new files
obsolete one  
update sendto locale list
> Per mozorg PR 175

- app/config/sources.inc.php
(Received translation from vendor, will add it as suggestions in Pontoon)
> Expose IHR email to Spanish

- app/config/locales.inc.php
- app/config/sources.inc.php
per email request by Melo46 <melo@carmu.com>, manager of Interlingua.
> add locale ia to mozilla.org files

- app/config/sources.inc.php
PR5118: quantum.lang for de
PR5121: developer-quantumn.lang
bug 1402209: add eo to firefox/nightly_whatsnew.lang
> add 2 new files, add locale eo to file

- app/config/sources.inc.php
Resort the order of the files.
> add new file FxnU_oct.lang per bug1407074

- app/config/sources.inc.php
add two more locales to monthly email project.
> add locales pt-BR, ru to new email file

- app/config/sources.inc.php
PR5150: nav bar strings
PR5159: Internet Health index page
PR5174: Dev quantum page: Ember -> Redux
PR5187: New download page for Fx57
PR5188: Firefox/channel/index.lang
PR5195: Firefox landing page
> add new files, update deadlines per mozorg PR#195

- app/config/sources.inc.php
- app/scripts/activate_firefox_shared
*Updates: Dev Quantum; firefox/feature/index
*New: Firefox Quantum redesign
*Update firefox/share activation list.
> add new file, update deadline, obsolete file per PR197

- app/config/sources.inc.php
*mozorg/home/index-2016: update deadline
*firefox/nightly_firstrun.lang: change to opt-in to support all firefox locales.
> mozorg PR205, fix bug1034049

- app/config/sources.inc.php
* foundation/advocacy.lang
* foundation/index.lang
* foundation/issues.lang
* foundation/leadership-network.lang
* mozorg/internet-health/decentralization.lang
* mozorg/internet-health/web-literacy.lang
> add locale sq to files per Bug1414743

- app/config/sources.inc.php
Add locale uk to file firefox/nightly_whatsnew.lang
> add locale uk to file per bug1420814

- app/config/sources.inc.php
* foundation/advocacy.lang
* foundation/index.lang
* foundation/issues.lang
* foundation/leadership-network.lang
* mozorg/internet-health/decentralization.lang
* mozorg/internet-health/index.lang
* mozorg/internet-health/privacy-security.lang
* mozorg/internet-health/web-literacy.lang
* thunderbird/channel.lang
> add locale ro to files per bug 1421078

- app/config/sources.inc.php
* mozorg/internet-health/index.lang
> add nn-NO to file per bug 1422650

- app/config/sources.inc.php
> Add firefox/new/reggiewatts.lang to German

- app/config/sources.inc.php
* firefox/hub/home.lang
* firefox/new/horizon.lang
* firefox/new/onboarding.lang
* firefox/products/android.lang
* firefox/products/desktop.lang
* firefox/products/developer.lang
* firefox/products/focus.lang
* firefox/products/ios.lang
* firefox/sync.lang
* firefox/whatsnew_42.lang
* firefox/whatsnew_50.lang
* mozorg/home/index-2016.lang
> Remove obsolete pages

- app/config/sources.inc.php
https://bugzilla.mozilla.org/show_bug.cgi?id=1433498#c1.
> remove fr, id per bug 1433498

- app/config/sources.inc.php
https://bugzilla.mozilla.org/show_bug.cgi?id=1433498#c1
> add fr and id to jan mail file per bug 1433498

- app/config/sources.inc.php
*add "ia" to files
** firefox/nightly_whatsnew.lang
** foundation/advocacy.lang
** foundation/index.lang
** foundation/issues.lang
** foundation/leadership-network.lang
*add manifesto deadline
> Bug1448647

- app/config/sources.inc.php
> add pt-PT to requested file per bug 1458112

- app/config/sources.inc.php
Version base: es, fr, pl, pt-BR, ru
Version b: de
Version c: id, zh-TW
> add may snippets entries per bug1459082

- app/config/sources.inc.php
#5755: MOSS update, hi-IN only
#5791: New, Privacy FAQ page; update Index page
#5793: Add form field strings to newsletter page
#5850 (replaces 5777): Privacy landing page update (no deadline)
#5857: Privacy update on Firefox channel pages (no deadline)
> add new file, update deadlines per PR235

- app/config/sources.inc.php
> Add fy-NL to file per Bug1479359

- app/config/sources.inc.php
* mozorg/internet-health/decentralization.lang
> add ia to IH files per bug1486262

- app/config/sources.inc.php
* firefox/products/developer-quantum.lang
> update deadline for PR243

- app/config/sources.inc.php
- Bug 1510839: add locales es-ES, fr, id, pl, pt-BR, ru to  newsletter/opt-out-confirmation.lang
- Bug 1511269: add gl to firefox/nightly_whatsnew.lang
> Add locales to files

- app/config/sources.inc.php
- add WNP 66 and deadline
- update privacy/index deadline.
> Add new file per PR 276

- app/config/sources.inc.php
> Add firefox/campaign.lan

- app/config/sources.inc.php
For https://github.com/mozilla-l10n/www.mozilla.org/pull/289
Attn: @peiying2
> Add lang file for Firefox 67 whatsnew

- app/config/sources.inc.php
mozilla-l10n PR: https://github.com/mozilla-l10n/www.mozilla.org/pull/297
> Add firefox/whatsnew_67.0.5.lang

- app/config/sources.inc.php
* mozorg/browser-history.lang
* mozorg/what-is-a-browser.lang
> add cs to two files per bug 1555723

- app/config/sources.inc.php
Ref: https://github.com/mozilla-l10n/www.mozilla.org/pull/310
> Add firefox/all-unified.lang

- app/config/sources.inc.php
See: https://github.com/mozilla-l10n/www.mozilla.org/pull/309
> Remove accounts.lang

- app/config/sources.inc.php
Ref: https://github.com/mozilla-l10n/www.mozilla.org/pull/321
> Add firefox/adblocker.lang

- app/config/sources.inc.php
Also remove priority and deadline fields, given they were only used in Webdashboard.
@TheoChevalier 
Can you check if I removed anything of yours?
> Clean engagement project

- app/config/sources.inc.php
Open question for nb-NO:
- There is one file, but it's not translated
- It was never enabled in Pontoon
Should it be kept and added to Pontoon instead?
> Clean up the list of locales for engagement

- app/config/sources.inc.php
Ref: https://github.com/mozilla/bedrock/pull/7447
> Remove mozorg/about.lang

- app/config/locales.inc.php
- app/config/sources.inc.php
l10n lang file: https://github.com/mozilla-l10n/www.mozilla.org/pull/329
> add lockwise page

- app/config/sources.inc.php
Ref: https://github.com/mozilla-l10n/www.mozilla.org/pull/332
> Add whatsnew 70

- app/config/sources.inc.php
add zh-TW to mozorg/browser-history.lang
> add zh-TW per bug1582770

- app/config/sources.inc.php
Fixing the locales so they are inline with the intended coverage.
> Fixing locales for lockwise

- app/config/sources.inc.php
Ref: https://github.com/mozilla/bedrock/issues/7864
> Remove firefox/accounts-2018.lang

- app/config/sources.inc.php
Strings in https://github.com/mozilla-l10n/www.mozilla.org/pull/340
This will be for French and German, translated in-house.
> Add firefox/welcome/page2.lang

- app/config/sources.inc.php
Ref: https://github.com/mozilla/bedrock/issues/8014
> Remove obsolete .lang files from mozorg

- app/config/sources.inc.php
The demo is here: https://bedrock-demo-errolyn.oregon-b.moz.works/en-US/firefox/mobile/
The bedrock PR is here: mozilla/bedrock#7957
The lang file PR: https://github.com/mozilla-l10n/www.mozilla.org/pull/346
> mobile-2019

- app/config/sources.inc.php
Prioritizing "tier 1" locales. We'll be getting French and German translations in-house. All others are opt-in.
> Add welcome pages 3 and 4

- app/config/sources.inc.php
Bedrock PR: https://github.com/mozilla/bedrock/pull/8159
> Add whatsnew_71.lang

- app/config/sources.inc.php
Ref: https://github.com/mozilla/bedrock/pull/8162
> Remove firefox/all.lang, add firefox/windows-64-bit.lang

- app/config/sources.inc.php
* mozorg/browser-history.lang
* mozorg/what-is-a-browser.lang
> add kab to files per bug1598916

- app/config/sources.inc.php
Lang file added in https://github.com/mozilla-l10n/www.mozilla.org/pull/359
> Add firefox/welcome/page5.lang

- app/config/sources.inc.php
Ref: https://github.com/mozilla-l10n/www.mozilla.org/pull/363
> Add firefox/set-default-thanks.lang

- app/config/sources.inc.php
> Use alphabetical order for firefox/set-default-thanks.lang

- app/config/sources.inc.php
Lang file added in https://github.com/mozilla-l10n/www.mozilla.org/pull/362
> Add community-hotline.lang

- app/config/sources.inc.php
Ref: https://github.com/mozilla-l10n/www.mozilla.org/pull/364
> Add firefox/whatsnew_73.lang and update firefox/set-default-thanks.lang

- app/config/sources.inc.php
Refs: 
firefox/browsers - https://github.com/mozilla-l10n/www.mozilla.org/pull/366
firefox/products - https://github.com/mozilla-l10n/www.mozilla.org/pull/367
> Add firefox/browsers.lang & firefox/products.lang

- app/config/sources.inc.php
Lang file added in https://github.com/mozilla-l10n/www.mozilla.org/pull/377
> Add whatsnew_74.lang

- app/config/sources.inc.php
Lang file added in https://github.com/mozilla-l10n/www.mozilla.org/pull/379
> Add whatsnew_75.lang

- app/config/sources.inc.php
strings here: https://github.com/mozilla-l10n/www.mozilla.org/pull/382/files
code here: https://github.com/mozilla/bedrock/pull/8655
Note: Eric will be adding French and German translations
> Add page 6 and 7

- app/config/sources.inc.php
add `uk` to mozorg/what-is-a-browser.lang
> add locale uk to file per bug1626279

- app/config/sources.inc.php
> add locale uk to file per bug1627046

- app/config/sources.inc.php
strings here: https://github.com/mozilla-l10n/www.mozilla.org/pull/387
> add enterprise

- app/config/sources.inc.php
Bedrock PR: https://github.com/mozilla/bedrock/pull/8782
L10N repo: https://github.com/mozilla-l10n/www.mozilla.org/pull/390
URL: https://www.mozilla.org/firefox/76.0/whatsnew/all/
> add whatsnew-76

- app/config/sources.inc.php
Lang file added in https://github.com/mozilla-l10n/www.mozilla.org/pull/394
> Add firefox/whatsnew_77.lang
